//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""KeyboardLeft"",
            ""id"": ""0a5a1989-a98e-4bb0-8c37-e10b2bc86e89"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""bed8cffc-ff0f-4968-915a-e9c960c9cfc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c1a09a7f-21d1-4abf-923a-fa03ecb2b872"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnRight"",
                    ""type"": ""Button"",
                    ""id"": ""ed34947f-9e33-41ed-982e-f04accbc0c21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractKill"",
                    ""type"": ""Button"",
                    ""id"": ""8c6f3110-71be-4fc3-9f8d-e8fb52153099"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ViewTask"",
                    ""type"": ""Button"",
                    ""id"": ""13e2db7d-9cb2-4c73-b780-a2a3d988fc16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2283ad0a-7280-4072-8935-e7eff1fe1c7f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abddaf06-9990-48d3-81ad-d8f9a2359e6c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9860433-4165-4844-ae10-4d9394e88c20"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ded08dad-dc9e-42b6-9627-840ccc314f66"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""InteractKill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1b25ac3-3985-4d77-bcdc-3693435813aa"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""ViewTask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KeyboardRight"",
            ""id"": ""267293a6-c2fd-4da7-b683-31b1ba07e349"",
            ""actions"": [
                {
                    ""name"": ""ViewTask"",
                    ""type"": ""Button"",
                    ""id"": ""1f6738fe-bcc5-46d7-bb71-f8d5685a2ba3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractKill"",
                    ""type"": ""Button"",
                    ""id"": ""4acb560e-b7bb-4115-9bb4-12cc3a819e87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnRight"",
                    ""type"": ""Button"",
                    ""id"": ""ad794a30-4e1e-4e78-989b-cc8787e7677b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnLeft"",
                    ""type"": ""Button"",
                    ""id"": ""54838cf7-944f-4ea1-9988-6fa9fad81ef8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""7ea96253-61f0-4fc8-97a5-d1262ad8941e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70dde6b7-07b4-4f10-afe3-1584c8e98489"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P1"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8848c71f-ea1b-41b6-b878-366ba2710f8d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P1"",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c185f94-1e80-443b-b16e-6e4825bbe2ca"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P1"",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b174ee6d-c463-4a58-b4ab-115b8f898b25"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0"",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""911ada2e-2f97-449a-b7b5-083bd841f89f"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P1;P0"",
                    ""action"": ""InteractKill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efe784f0-de80-424a-8189-b6807a5e6389"",
                    ""path"": ""<Keyboard>/backslash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P1"",
                    ""action"": ""ViewTask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GamePad"",
            ""id"": ""9fc08146-8b67-4bd5-987d-cefa523bb1df"",
            ""actions"": [
                {
                    ""name"": ""ViewTask"",
                    ""type"": ""Button"",
                    ""id"": ""5470c5d2-2952-4118-a1ad-0e118f14d5ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractKill"",
                    ""type"": ""Button"",
                    ""id"": ""d86e540f-4390-466f-989b-cf6010a1721f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnRight"",
                    ""type"": ""Button"",
                    ""id"": ""a5b27a64-172b-47d9-9c83-bff38cc0cd62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnLeft"",
                    ""type"": ""Button"",
                    ""id"": ""ba676f94-468e-4ada-8c27-cb12b8bf27ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""5d1c9604-ae46-4f54-ade2-5c943420cf43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ace95530-13af-4ae4-a2dd-52a02e64bf64"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P0;P3"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cf05db6-68dc-4f8f-aa11-ca40dfd16ea2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P3;P0"",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a716f7a3-1d64-4c6b-b6eb-c67cc424390f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P3;P0"",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8e9c866-0fe0-44ae-ac20-2a1ec47d67aa"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P3;P0"",
                    ""action"": ""InteractKill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e93e838e-29e5-4051-8c7c-3525a5bc0167"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""P3;P0"",
                    ""action"": ""ViewTask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""P0"",
            ""bindingGroup"": ""P0"",
            ""devices"": []
        },
        {
            ""name"": ""P1"",
            ""bindingGroup"": ""P1"",
            ""devices"": []
        },
        {
            ""name"": ""P2"",
            ""bindingGroup"": ""P2"",
            ""devices"": []
        },
        {
            ""name"": ""P3"",
            ""bindingGroup"": ""P3"",
            ""devices"": []
        }
    ]
}");
        // KeyboardLeft
        m_KeyboardLeft = asset.FindActionMap("KeyboardLeft", throwIfNotFound: true);
        m_KeyboardLeft_Move = m_KeyboardLeft.FindAction("Move", throwIfNotFound: true);
        m_KeyboardLeft_TurnLeft = m_KeyboardLeft.FindAction("TurnLeft", throwIfNotFound: true);
        m_KeyboardLeft_TurnRight = m_KeyboardLeft.FindAction("TurnRight", throwIfNotFound: true);
        m_KeyboardLeft_InteractKill = m_KeyboardLeft.FindAction("InteractKill", throwIfNotFound: true);
        m_KeyboardLeft_ViewTask = m_KeyboardLeft.FindAction("ViewTask", throwIfNotFound: true);
        // KeyboardRight
        m_KeyboardRight = asset.FindActionMap("KeyboardRight", throwIfNotFound: true);
        m_KeyboardRight_ViewTask = m_KeyboardRight.FindAction("ViewTask", throwIfNotFound: true);
        m_KeyboardRight_InteractKill = m_KeyboardRight.FindAction("InteractKill", throwIfNotFound: true);
        m_KeyboardRight_TurnRight = m_KeyboardRight.FindAction("TurnRight", throwIfNotFound: true);
        m_KeyboardRight_TurnLeft = m_KeyboardRight.FindAction("TurnLeft", throwIfNotFound: true);
        m_KeyboardRight_Move = m_KeyboardRight.FindAction("Move", throwIfNotFound: true);
        // GamePad
        m_GamePad = asset.FindActionMap("GamePad", throwIfNotFound: true);
        m_GamePad_ViewTask = m_GamePad.FindAction("ViewTask", throwIfNotFound: true);
        m_GamePad_InteractKill = m_GamePad.FindAction("InteractKill", throwIfNotFound: true);
        m_GamePad_TurnRight = m_GamePad.FindAction("TurnRight", throwIfNotFound: true);
        m_GamePad_TurnLeft = m_GamePad.FindAction("TurnLeft", throwIfNotFound: true);
        m_GamePad_Move = m_GamePad.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyboardLeft
    private readonly InputActionMap m_KeyboardLeft;
    private List<IKeyboardLeftActions> m_KeyboardLeftActionsCallbackInterfaces = new List<IKeyboardLeftActions>();
    private readonly InputAction m_KeyboardLeft_Move;
    private readonly InputAction m_KeyboardLeft_TurnLeft;
    private readonly InputAction m_KeyboardLeft_TurnRight;
    private readonly InputAction m_KeyboardLeft_InteractKill;
    private readonly InputAction m_KeyboardLeft_ViewTask;
    public struct KeyboardLeftActions
    {
        private @PlayerInput m_Wrapper;
        public KeyboardLeftActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_KeyboardLeft_Move;
        public InputAction @TurnLeft => m_Wrapper.m_KeyboardLeft_TurnLeft;
        public InputAction @TurnRight => m_Wrapper.m_KeyboardLeft_TurnRight;
        public InputAction @InteractKill => m_Wrapper.m_KeyboardLeft_InteractKill;
        public InputAction @ViewTask => m_Wrapper.m_KeyboardLeft_ViewTask;
        public InputActionMap Get() { return m_Wrapper.m_KeyboardLeft; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardLeftActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardLeftActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardLeftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardLeftActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @TurnLeft.started += instance.OnTurnLeft;
            @TurnLeft.performed += instance.OnTurnLeft;
            @TurnLeft.canceled += instance.OnTurnLeft;
            @TurnRight.started += instance.OnTurnRight;
            @TurnRight.performed += instance.OnTurnRight;
            @TurnRight.canceled += instance.OnTurnRight;
            @InteractKill.started += instance.OnInteractKill;
            @InteractKill.performed += instance.OnInteractKill;
            @InteractKill.canceled += instance.OnInteractKill;
            @ViewTask.started += instance.OnViewTask;
            @ViewTask.performed += instance.OnViewTask;
            @ViewTask.canceled += instance.OnViewTask;
        }

        private void UnregisterCallbacks(IKeyboardLeftActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @TurnLeft.started -= instance.OnTurnLeft;
            @TurnLeft.performed -= instance.OnTurnLeft;
            @TurnLeft.canceled -= instance.OnTurnLeft;
            @TurnRight.started -= instance.OnTurnRight;
            @TurnRight.performed -= instance.OnTurnRight;
            @TurnRight.canceled -= instance.OnTurnRight;
            @InteractKill.started -= instance.OnInteractKill;
            @InteractKill.performed -= instance.OnInteractKill;
            @InteractKill.canceled -= instance.OnInteractKill;
            @ViewTask.started -= instance.OnViewTask;
            @ViewTask.performed -= instance.OnViewTask;
            @ViewTask.canceled -= instance.OnViewTask;
        }

        public void RemoveCallbacks(IKeyboardLeftActions instance)
        {
            if (m_Wrapper.m_KeyboardLeftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardLeftActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardLeftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardLeftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardLeftActions @KeyboardLeft => new KeyboardLeftActions(this);

    // KeyboardRight
    private readonly InputActionMap m_KeyboardRight;
    private List<IKeyboardRightActions> m_KeyboardRightActionsCallbackInterfaces = new List<IKeyboardRightActions>();
    private readonly InputAction m_KeyboardRight_ViewTask;
    private readonly InputAction m_KeyboardRight_InteractKill;
    private readonly InputAction m_KeyboardRight_TurnRight;
    private readonly InputAction m_KeyboardRight_TurnLeft;
    private readonly InputAction m_KeyboardRight_Move;
    public struct KeyboardRightActions
    {
        private @PlayerInput m_Wrapper;
        public KeyboardRightActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ViewTask => m_Wrapper.m_KeyboardRight_ViewTask;
        public InputAction @InteractKill => m_Wrapper.m_KeyboardRight_InteractKill;
        public InputAction @TurnRight => m_Wrapper.m_KeyboardRight_TurnRight;
        public InputAction @TurnLeft => m_Wrapper.m_KeyboardRight_TurnLeft;
        public InputAction @Move => m_Wrapper.m_KeyboardRight_Move;
        public InputActionMap Get() { return m_Wrapper.m_KeyboardRight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardRightActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardRightActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardRightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardRightActionsCallbackInterfaces.Add(instance);
            @ViewTask.started += instance.OnViewTask;
            @ViewTask.performed += instance.OnViewTask;
            @ViewTask.canceled += instance.OnViewTask;
            @InteractKill.started += instance.OnInteractKill;
            @InteractKill.performed += instance.OnInteractKill;
            @InteractKill.canceled += instance.OnInteractKill;
            @TurnRight.started += instance.OnTurnRight;
            @TurnRight.performed += instance.OnTurnRight;
            @TurnRight.canceled += instance.OnTurnRight;
            @TurnLeft.started += instance.OnTurnLeft;
            @TurnLeft.performed += instance.OnTurnLeft;
            @TurnLeft.canceled += instance.OnTurnLeft;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IKeyboardRightActions instance)
        {
            @ViewTask.started -= instance.OnViewTask;
            @ViewTask.performed -= instance.OnViewTask;
            @ViewTask.canceled -= instance.OnViewTask;
            @InteractKill.started -= instance.OnInteractKill;
            @InteractKill.performed -= instance.OnInteractKill;
            @InteractKill.canceled -= instance.OnInteractKill;
            @TurnRight.started -= instance.OnTurnRight;
            @TurnRight.performed -= instance.OnTurnRight;
            @TurnRight.canceled -= instance.OnTurnRight;
            @TurnLeft.started -= instance.OnTurnLeft;
            @TurnLeft.performed -= instance.OnTurnLeft;
            @TurnLeft.canceled -= instance.OnTurnLeft;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IKeyboardRightActions instance)
        {
            if (m_Wrapper.m_KeyboardRightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardRightActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardRightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardRightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardRightActions @KeyboardRight => new KeyboardRightActions(this);

    // GamePad
    private readonly InputActionMap m_GamePad;
    private List<IGamePadActions> m_GamePadActionsCallbackInterfaces = new List<IGamePadActions>();
    private readonly InputAction m_GamePad_ViewTask;
    private readonly InputAction m_GamePad_InteractKill;
    private readonly InputAction m_GamePad_TurnRight;
    private readonly InputAction m_GamePad_TurnLeft;
    private readonly InputAction m_GamePad_Move;
    public struct GamePadActions
    {
        private @PlayerInput m_Wrapper;
        public GamePadActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ViewTask => m_Wrapper.m_GamePad_ViewTask;
        public InputAction @InteractKill => m_Wrapper.m_GamePad_InteractKill;
        public InputAction @TurnRight => m_Wrapper.m_GamePad_TurnRight;
        public InputAction @TurnLeft => m_Wrapper.m_GamePad_TurnLeft;
        public InputAction @Move => m_Wrapper.m_GamePad_Move;
        public InputActionMap Get() { return m_Wrapper.m_GamePad; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePadActions set) { return set.Get(); }
        public void AddCallbacks(IGamePadActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePadActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePadActionsCallbackInterfaces.Add(instance);
            @ViewTask.started += instance.OnViewTask;
            @ViewTask.performed += instance.OnViewTask;
            @ViewTask.canceled += instance.OnViewTask;
            @InteractKill.started += instance.OnInteractKill;
            @InteractKill.performed += instance.OnInteractKill;
            @InteractKill.canceled += instance.OnInteractKill;
            @TurnRight.started += instance.OnTurnRight;
            @TurnRight.performed += instance.OnTurnRight;
            @TurnRight.canceled += instance.OnTurnRight;
            @TurnLeft.started += instance.OnTurnLeft;
            @TurnLeft.performed += instance.OnTurnLeft;
            @TurnLeft.canceled += instance.OnTurnLeft;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IGamePadActions instance)
        {
            @ViewTask.started -= instance.OnViewTask;
            @ViewTask.performed -= instance.OnViewTask;
            @ViewTask.canceled -= instance.OnViewTask;
            @InteractKill.started -= instance.OnInteractKill;
            @InteractKill.performed -= instance.OnInteractKill;
            @InteractKill.canceled -= instance.OnInteractKill;
            @TurnRight.started -= instance.OnTurnRight;
            @TurnRight.performed -= instance.OnTurnRight;
            @TurnRight.canceled -= instance.OnTurnRight;
            @TurnLeft.started -= instance.OnTurnLeft;
            @TurnLeft.performed -= instance.OnTurnLeft;
            @TurnLeft.canceled -= instance.OnTurnLeft;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IGamePadActions instance)
        {
            if (m_Wrapper.m_GamePadActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePadActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePadActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePadActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePadActions @GamePad => new GamePadActions(this);
    private int m_P0SchemeIndex = -1;
    public InputControlScheme P0Scheme
    {
        get
        {
            if (m_P0SchemeIndex == -1) m_P0SchemeIndex = asset.FindControlSchemeIndex("P0");
            return asset.controlSchemes[m_P0SchemeIndex];
        }
    }
    private int m_P1SchemeIndex = -1;
    public InputControlScheme P1Scheme
    {
        get
        {
            if (m_P1SchemeIndex == -1) m_P1SchemeIndex = asset.FindControlSchemeIndex("P1");
            return asset.controlSchemes[m_P1SchemeIndex];
        }
    }
    private int m_P2SchemeIndex = -1;
    public InputControlScheme P2Scheme
    {
        get
        {
            if (m_P2SchemeIndex == -1) m_P2SchemeIndex = asset.FindControlSchemeIndex("P2");
            return asset.controlSchemes[m_P2SchemeIndex];
        }
    }
    private int m_P3SchemeIndex = -1;
    public InputControlScheme P3Scheme
    {
        get
        {
            if (m_P3SchemeIndex == -1) m_P3SchemeIndex = asset.FindControlSchemeIndex("P3");
            return asset.controlSchemes[m_P3SchemeIndex];
        }
    }
    public interface IKeyboardLeftActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnTurnLeft(InputAction.CallbackContext context);
        void OnTurnRight(InputAction.CallbackContext context);
        void OnInteractKill(InputAction.CallbackContext context);
        void OnViewTask(InputAction.CallbackContext context);
    }
    public interface IKeyboardRightActions
    {
        void OnViewTask(InputAction.CallbackContext context);
        void OnInteractKill(InputAction.CallbackContext context);
        void OnTurnRight(InputAction.CallbackContext context);
        void OnTurnLeft(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IGamePadActions
    {
        void OnViewTask(InputAction.CallbackContext context);
        void OnInteractKill(InputAction.CallbackContext context);
        void OnTurnRight(InputAction.CallbackContext context);
        void OnTurnLeft(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
